name: Debug
on:
  pull_request:
    # synchronize - when new commits are added
    types: [opened, synchronize, closed]
jobs:
  output-debug:
    runs-on: ubuntu-18.04
    steps:
      - uses: jpfm-actions/github-action-explore-debug@main
      # - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          jq_selector: ".pull_request"
          example: ${{ secrets.EXAMPLE }}
